cc/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
import dash.views
import front.views

urlpatterns = [
    path('dash/', include('dash.urls')),
    path('editor', include('editor.urls')),
    path('', include('front.urls')),
    path('ajax/check-answer', dash.views.checkAnswer, name="check-answer"),
    path('ajax/update-progress', dash.views.updateLessonProgress, name="update-progress"),
    path('ajax/award-badge', dash.views.awardBadge, name='award-badge'),
    path('ajax/view-notifications', dash.views.notificationSeen, name='notification-seen'),
    path('ajax/get-notifications', dash.views.getNotifications, name='getNotifications'),
    path('chat/', include('chat.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dash/urls.py
from django.urls import path
from . import views
from django.conf import settings


app_name = "dash"
urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logoutView, name="logout"),
    path('projects', views.projectView, name='projects'),
    path('projects/<slug>', views.projectLessonView, name="project-slug"),
    path('<project>/<lesson>', views.workflow, name="project-lesson"),
    path('trophies', views.trophy, name='trophies'),
    path('community', views.community, name='community'),
    path('activity', views.activity, name="activity"),
    path('editor', views.editor, name="editor"),
    path('notifications', views.notifications, name='notifications'),
    path('leaderboards', views.leaderboards, name="leaderboards"),
    path('settings', views.settings, name='settings'),
    path('password', views.password_settings, name='password-change')
]

front/urls.py
from django.urls import path, include
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from .forms import ResetForm, ResetPassword

app_name = "front"
urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/login/', views.loginView, name="login"),
    path('accounts/signup', views.signup, name="signup"), 
    path('accounts/reset/', auth_views.PasswordResetView.as_view(form_class=ResetForm, success_url="done", template_name='front/forgot.html', email_template_name = 'front/reset_password_email.html'), name="password_reset"),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('front:password_reset_complete'), form_class=ResetPassword, template_name='front/forgot-reset.html'), name="password_reset_confirm"),
    path('accounts/reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='front/forgot-complete.html'), name="password_reset_complete")  ,
    path('accounts/reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='front/forgot-done.html'), name="password_reset_done"),
]

front/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User


def user_exists(username):
    return User.objects.filter(username=username).exists()

class NewUserForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class' : 'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'type': 'password', 'class' : 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'type': 'password', 'class' : 'form-control'}))

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "password1", "password2")

    def clean_email(self):
        data = self.cleaned_data.get("email")

        if user_exists(data):
            raise forms.ValidationError("Email already exists. Try logging in!")

        return data

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.username = self.cleaned_data["email"]
        user.set_password(self.cleaned_data["password1"])
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class ResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class' : 'form-control'}))

    class Meta:
        model = User
        fields = ("email")

class ResetPassword(SetPasswordForm):
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'type': 'password', 'class' : 'form-control'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'type': 'password', 'class' : 'form-control'}))

    class Meta:
        model = User
        fields = ("new_password1", "new_password2")

front/views.py
# Imports from Django 
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib import messages

# Imports from app
from .forms import NewUserForm, ResetForm
from cc.settings import EMAIL_HOST_USER


# Create your views here.
def index(request):
    if request.method == 'POST':
        # User new user form
        form = NewUserForm(request.POST)
        # Form valid
        if form.is_valid():
            # Save form
            user = form.save()
            messages.success(request, 'Your account was successfully registered!')
            return redirect(reverse('front:login'))
    else:
        form = NewUserForm()
    return render(request, 'front/index.html', {'form': form})

def loginView(request):
    if request.method == 'POST':
        uname = request.POST.get('cc-email')
        pwd = request.POST.get('cc-password')
        # Authenticate user using Django authentication function
        user = authenticate(username=uname, password=pwd)
        # Check user exists
        if user is not None:
            # Log in user
            login(request, user)
            return redirect('dash:index')
        else:
            messages.error(request,'Username / Password was incorrect!')
            return redirect('front:login')           

    return render(request, 'front/login.html', {})

# Sign up
def signup(request):
    if request.method == 'POST':
        # New User Form
        form = NewUserForm(request.POST)
        # If form is valid       
        if form.is_valid():
            # save form 
            user = form.save()
            messages.success(request, 'Your account was successfully registered!')
            return redirect(reverse('front:login'))
    else:
        form = NewUserForm()
    return render(request, 'front/register.html', {'form': form})

front/templates/front/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="{% static "front/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "front/pricing.css" %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <title>{% block title %}{% endblock %} | CodeController</title>
</head>

<body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <div class="mx-auto order-0">
                    <a class="navbar-brand float-left" href="{% url 'front:index' %}">CodeController <i class="fas fa-terminal"></i></a>
                    <button class="btn-sm navbar-toggler float-right" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                    <ul class="navbar-nav ml-auto">
                        {% if request.user.is_authenticated %}
                        <li class="nav-item text-center mt-2">
                            <a class="btn btn-info" href="{% url 'dash:index' %}">Dashboard</a>
                        </li>
                        {% else %}
                        <li class="nav-item text-center mt-2">
                            <a class="nav-link mr-2" href="{% url 'front:signup' %}">Sign up</a>
                        </li>
                        <li class="nav-item text-center mt-2">
                            <a class="btn btn-info" href="{% url 'front:login' %}">Log in</a>
                        </li>
                        {% endif %} 
                    </ul>
                </div>
            </nav>
   
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- Footer content -->
    
<footer class="container py-5">
        <hr></hr>
        <div class="row">
          <div class="col-12 col-md">
       
            <small class="d-block mb-3 text-muted">&copy; CodeController <i class="fas fa-terminal"></i> 2020</small>
          </div>
          <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Help</a></li>
              <li><a class="text-muted" href="#">Blog</a></li>
              <li><a class="text-muted" href="#">Mission</a></li>
              <li><a class="text-muted" href="#">GitHub</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>CodeController</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">About</a></li>
              <li><a class="text-muted" href="#">Team</a></li>
              <li><a class="text-muted" href="#">Privacy</a></li>
              <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
                <h5>Popular Courses</h5>
                <ul class="list-unstyled text-small">
                  <li><a class="text-muted" href="#">Python</a></li>
                  <li><a class="text-muted" href="#">Electrical Engineering</a></li>
                  <li><a class="text-muted" href="#">HTML</a></li>
                  <li><a class="text-muted" href="#">CSS</a></li>
                </ul>
              </div>
        </div>
      </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

front/templates/front/forgot-complete.html
{% extends 'front/base.html' %}
{% block title %}Reset Password{% endblock %}

<!-- Start main content -->
{% block content%}

<div class="row">
    <div class="col-sm-12 mt-4">
        <h1 class="text-center text-dark">Password Reset</h1>
    </div>
    <div class="col-sm-12 mt-5 mb-5">
        <div class="mx-auto">
                    <div class="row">
                        <div class="col-sm-12">
                            <p class="text-center">Your password has been set. You may go ahead and log in now.</p>
                            <p class="text-center"><a href="{% url 'front:login' %}" class="text-center btn btn-primary">Log in</a></p>
                        </div>
                    </div>
        </div>
        
    </div>
</div>

{% endblock %}

front/templates/front/forgot-done.html
{% extends 'front/base.html' %}
{% block title %}Reset Password{% endblock %}

<!-- Start main content -->
{% block content%}

<div class="row">
    <div class="col-sm-12 mt-4">
        <h1 class="text-center text-dark">Password Reset Sent</h1>
    </div>
    <div class="col-sm-12 mt-5 mb-5">
        <div class="mx-auto">
                    <div class="row">
                        <div class="col-sm-12">
                           <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
                           <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
                        </div>
                    </div>
        </div>
        
    </div>
</div>

{% endblock %}

front/templates/front/forgot-reset.html
{% extends 'front/base.html' %}
{% load i18n static %}
{% block title %}Reset Password{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-12 mt-4">
        <h1 class="text-center text-dark">Password Reset</h1>
    </div>
    <div class="col-sm-12 mt-5 mb-5">
        <div class="w-50 mx-auto">
            {% if validlink %}

            <p>Please enter your new password twice so we can verify you typed it in correctly.</p>

                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group has-error">
                                <label class="control-label" for="inputError">Password</label>
                                {{ form.new_password1 }}
                                <span class="help-block">
                                    {% if form.new_password1.errors %}
                                        <small class="text-danger">{{ form.new_password1.errors|striptags }}</small>
                                    {% endif %}
                                </span>
                              </div> 
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group has-error">
                                <label class="control-label" for="inputError">Password Again</label>
                                {{ form.new_password2 }}
                                <span class="help-block">
                                    {% if form.new_password2.errors %}
                                        <small class="text-danger">{{ form.new_password2.errors|striptags }}</small>
                                    {% endif %}
                                </span>
                              </div> 
                        </div>
                    </div>
                        <button type="submit" class="btn btn-lg btn-info btn-block mt-4">Reset Password</button>
                    </form>

                    {% else %}

                    <p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>

                    {% endif %}
                    <p class="float-right mt-4"><a class="text-dark" href="{% url 'front:signup' %}">Not signed up yet? Start for free</a></p>
        </div>
        
    </div>
</div>

{% endblock %}

front/templates/front/forgot.html
{% extends 'front/base.html' %}
{% block title %}Reset Password{% endblock %}

<!-- Start main content -->
{% block content%}

<div class="row">
    <div class="col-sm-12 mt-4">
        <h1 class="text-center text-dark">Forgot your password?</h1>
    </div>
    <div class="col-sm-12 mt-5 mb-5">
        <div class="w-50 mx-auto">
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group has-error">
                                <label class="control-label" for="inputError">Email Address</label>
                                {{ form.email }}
                                <span class="help-block">
                                    {% if form.email.errors %}
                                        <small class="text-danger">{{ form.email.errors|striptags }}</small>
                                    {% endif %}
                                </span>
                              </div>
                        </div>
                    </div>
                        <button type="submit" class="btn btn-lg btn-info btn-block mt-4">Reset Password</button>
                    </form>
                    <p class="float-right mt-4"><a class="text-dark" href="{% url 'front:signup' %}">Not signed up yet? Start for free</a></p>
        </div>
        
    </div>
</div>

{% endblock %}

front/templates/front/index.html
{% extends 'front/base.html' %}
{% block title %}Learn. Code. Control. {% endblock %}

<!-- Start main content -->
{% block content%}
<div class="row">
    <div class="col-sm-12 mt-4">
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible"{% endif %}>{{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                    </div>
                {% endfor %}
        {% endif %}
        <h1 class="text-center text-dark">Learn. Code. Control.</h1>
    </div>
    <div class="col-sm-12 col-md-6 mt-4">
    <div class="card">
                <img src="https://static.seattletimes.com/wp-content/uploads/2015/12/3904d112-88bf-11e5-8ed4-75bd9fe05d05-780x520.jpg" class="card-img-top" alt="...">
                <div class="card-body bg-info">
                  <p class="card-text text-white">"Everybody should learn to program, it teaches you how to think" - Steve Jobs</p>
                </div>
              </div>
    </div>
    <div class="col-sm-12 col-md-6 mt-4">
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group has-error">
                        <label class="control-label" for="inputError">Email Address</label>
                        {{ form.email }}
                        <span class="help-block">
                            {% if form.email.errors %}
                                <small class="text-danger">{{ form.email.errors|striptags }}</small>
                            {% endif %}
                        </span>
                      </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group has-error">
                        <label class="control-label" for="inputError">First Name</label>
                        {{ form.first_name }}
                        <span class="help-block">
                            {% if form.first_name.errors %}
                                <small class="text-danger">{{ form.first_name.errors|striptags }}</small>
                            {% endif %}
                        </span>
                      </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group has-error">
                        <label class="control-label" for="inputError">Last Name</label>
                        {{ form.last_name }}
                        <span class="help-block">
                            {% if form.last_name.errors %}
                                <small class="text-danger">{{ form.last_name.errors|striptags }}</small>
                            {% endif %}
                        </span>
                      </div>
                </div>
                <div class="col-sm-12">
                    <div class="form-group has-error">
                        <label class="control-label" for="inputError">Password</label>
                        {{ form.password1 }}
                        <span class="help-block">
                            {% if form.password1.errors %}
                                <small class="text-danger">{{ form.password1.errors|striptags }}</small>
                            {% endif %}
                        </span>
                      </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group has-error">
                            <label class="control-label" for="inputError">Password Again</label>
                            {{ form.password2 }}
                            <span class="help-block">
                                {% if form.password2.errors %}
                                    <small class="text-danger">{{ form.password2.errors|striptags }}</small>
                                {% endif %}
                            </span>
                          </div>
                        </div>
                    <div class="col-sm-12">
                            <button type="submit" class="btn btn-info btn-block">Get Coding Now</button>
                        </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

front/templates/front/lessons.html
{% extends 'front/base.html' %}
{% block title%}Courses{% endblock %}
{% block lessons-active%}active{% endblock%}

{% block content %}

<div class="row">
        <div class="col-sm-12 mt-4">
            <h1 class="text-center text-dark">The Real Curriculum</h1>
        </div>
        <div class="col-sm-12 mt-4">
            <h3 class="text-dark text-uppercase">challenge yourself</h3>
            <div class="card mb-3 mt-4">
                <div class="row no-gutters">
                    <div class="col-md-2">
                        <img src="https://via.placeholder.com/220x200?text=Course%20Image%20Here" class="card-img" alt="...">
                    </div>
                    <div class="col-md-10">
                        <div class="card-body">
                            <h5 class="card-title">Control RC Vehicle from your own web-app</h5>
                            <p class="card-text">This project will bring you on the amalgamation of hardware and software, we recommend completing our other courses before embarking on this pathway.</p>
                            <p class="card-text"><small class="text-muted">Added 1 week ago</small></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            <hr>
            <h3 class="text-dark text-uppercase">Start the joruney today</h3>
        </div>
        <div class="col-sm-4 mt-4">
                <div class="card mb-3">
                        <div class="row no-gutters">
                            <div class="col-md-12">
                                <div class="card-body">
                                    <h5 class="card-title">Python</h5>
                                    <p class="card-text">Course Description</p>
                                    <p class="card-text"><small class="text-muted">Added 1 week ago</small></p>
                                </div>
                            </div>
                        </div>
                    </div>
        </div>
        <div class="col-sm-4 mt-4">
                <div class="card mb-3">
                        <div class="row no-gutters">
                            <div class="col-md-12">
                                <div class="card-body">
                                    <h5 class="card-title">Electrical Engineering</h5>
                                    <p class="card-text">Course Description</p>
                                    <p class="card-text"><small class="text-muted">Added 1 week ago</small></p>
                                </div>
                            </div>
                        </div>
                    </div>
        </div>
        <div class="col-sm-4 mt-4">
                <div class="card mb-3">
                        <div class="row no-gutters">
                            <div class="col-md-12">
                                <div class="card-body">
                                    <h5 class="card-title">Web Development - Basics</h5>
                                    <p class="card-text">Course Description</p>
                                    <p class="card-text"><small class="text-muted">Added 1 week ago</small></p>
                                </div>
                            </div>
                        </div>
                    </div>
        </div>

        
        

        <!-- Another card-->
    </div>
{% endblock %}

front/templates/front/login.html
{% extends 'front/base.html' %}
{% block title %}Log in{% endblock %}

<!-- Start main content -->
{% block content%}

<div class="row">
    <div class="col-sm-12 mt-4">
        <h1 class="text-center text-dark">Log In to CodeController</h1>
    </div>
    <div class="col-sm-12 mt-4 align-items-center">
                <div class="w-100 mx-auto">
                    {% if messages %}
                    {% for message in messages %}
                        <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible"{% endif %}>{{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                      </button>
                        </div>
                    {% endfor %}
            {% endif %}
                        <form action="" method="POST">
                            {% csrf_token %}
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label for="cc-email">Email:</label>
                                            <input type="text" name="cc-email" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                            <div class="form-group">
                                                <label for="cc-password">Password:</label>
                                                <input type="password" name="cc-password" class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-sm-12">
                                                <a class="text-info mt-4" href="{% url 'front:password_reset' %}">Forgot my password?</a>
                                                <button type="submit" class="btn btn-lg btn-info btn-block font-weight-bold mt-4">Log in</button>
                                            </div>
                                </div>
                            </form>
                            <p class="float-right mt-4"><a class="text-info font-weight-bold" href="{% url 'front:signup' %}">Not signed up yet? Start for free</a></p>
                </div>
        </div>
    </div>
</div>


{% endblock %}

front/templates/front/reset_password_email.html
{% load i18n %}{% autoescape off %}
	{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
	
	{% trans "Please go to the following page and choose a new password:" %}
	{% block reset_link %}
	{{ protocol }}://{{ domain }}{% url 'front:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
    {% trans 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}
	
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}