cc/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
import dash.views
import front.views

urlpatterns = [
    path('dash/', include('dash.urls')),
    path('editor', include('editor.urls')),
    path('', include('front.urls')),
    path('ajax/check-answer', dash.views.checkAnswer, name="check-answer"),
    path('ajax/update-progress', dash.views.updateLessonProgress, name="update-progress"),
    path('ajax/award-badge', dash.views.awardBadge, name='award-badge'),
    path('ajax/view-notifications', dash.views.notificationSeen, name='notification-seen'),
    path('ajax/get-notifications', dash.views.getNotifications, name='getNotifications'),
    path('chat/', include('chat.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dash/urls.py
from django.urls import path
from . import views
from django.conf import settings


app_name = "dash"
urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logoutView, name="logout"),
    path('projects', views.projectView, name='projects'),
    path('projects/<slug>', views.projectLessonView, name="project-slug"),
    path('<project>/<lesson>', views.workflow, name="project-lesson"),
    path('trophies', views.trophy, name='trophies'),
    path('community', views.community, name='community'),
    path('activity', views.activity, name="activity"),
    path('editor', views.editor, name="editor"),
    path('notifications', views.notifications, name='notifications'),
    path('leaderboards', views.leaderboards, name="leaderboards"),
    path('settings', views.settings, name='settings'),
    path('password', views.password_settings, name='password-change')
]

editor/urls.py
from django.urls import path
from . import views

app_name = "editor"
urlpatterns = [
    path('', views.index, name='index'),
]

activity/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Stream(models.Model):
    actor = models.ForeignKey(User, on_delete=models.CASCADE)
    verb = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    link = models.CharField(max_length=255)
    when = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s %s %s" % (self.actor, self.verb, self.title)

    def new(actor, verb, title, link):
        Stream.objects.create(
            actor=actor,
            verb=verb,
            title=title,
            link=link
            )

dash/models.py
from django.db import models
from django.utils.text import Truncator, slugify
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from ckeditor.fields import RichTextField
import uuid

# Course table
class Course(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    s = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def short(self):
        return Truncator(self.description).chars(50)

    def save(self, *args, **kwargs):
        self.s = slugify(self.title)
        return super(Course, self).save(*args, **kwargs)

# Lesson table
class Lesson(models.Model):
    title = models.CharField(max_length=255)
    content = RichTextField(blank=True, null=True, config_name="special")
    shortDesc = models.CharField(max_length=255)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    s = models.SlugField(unique=True)    

    def __str__(self):
        return "%s - %s" % (self.title, self.course.title)

    def short(self):
        return Truncator(self.shortDesc).chars(50)

    def save(self, *args, **kwargs):
        self.s = slugify(self.title)
        super(Lesson, self).save(*args, **kwargs)

# Instructions table
class Instructions(models.Model):
    title = models.CharField(max_length=255)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)

    def __str__(self):
        return "%s - (%s / %s)" % (self.title, self.lesson.title, self.lesson.course.title)

    class Meta:
        verbose_name_plural = "Lesson Instructions"

# Lesson Progress table
class LessonProgress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)
    start = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    finish = models.DateTimeField(null=True, blank=True, auto_now=True)

    def __str__(self):
        return "%s - %s" % (self.user.get_full_name(), self.lesson.title)

    def percent(self):
        total = LessonProgress.objects.filter(lesson__course=self.lesson.course, user=self.user).count()
        done = LessonProgress.objects.filter(lesson__course=self.lesson.course, user=self.user, completed=True).count()
        return (done/total)*100

    class Meta:
        verbose_name_plural = "Lesson Progression"

# Quiz table
class Quiz(models.Model):
    title = models.CharField(max_length=255)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Quizes"

# Quiz Questions table
class QuizQuestion(models.Model):
    title = models.CharField(max_length=255)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    def __str__(self):
        return "%s: %s" % (self.quiz.title, self.title)

    class Meta:
        verbose_name_plural = "Quiz Questions"

# Quiz Answers table
class QuizAnswer(models.Model):
    title = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(QuizQuestion, on_delete=models.CASCADE)

    def __str__(self):
        return "%s: %s - %s" % (self.question.quiz.title, self.question.title, self.title)

    class Meta:
        verbose_name_plural = "Question Answers"

dash/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm

# Extension to style Django UserChangeForm
class EditProfileForm(UserChangeForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class' : 'form-control', 'aria-describedby': 'emailHelp'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))

    class Meta:
        model = User
        fields = {
            'email',
            'first_name',
            'last_name'
        }

# Extentsion to style Django PasswordChangeForm
class EditPasswordForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'type': 'password',  'class' : 'form-control', 'aria-describedby': 'emailHelp'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'type': 'password', 'class' : 'form-control'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'type': 'password', 'class' : 'form-control'}))

    class Meta:
        model = User
        fields = {
            'old_password',
            'new_password1',
            'new_password2'
        }

activity/views.py
from django.shortcuts import render

# Create your views here.

dash/views.py
# Django imports
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib import messages
from django.http import JsonResponse
from django.utils.safestring import mark_safe
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

# Import from app models and python
from .models import Course, Lesson, LessonProgress, Quiz, QuizQuestion, QuizAnswer
from badges.models import Trophies, Award
from .forms import EditProfileForm, EditPasswordForm
from activity.models import Stream
from notifications.models import Notification
import json

@login_required # Login decorator from Django
def index(request):
    # Get all courses
    c = Course.objects.all()

    # Pass courses object
    context = {'courses': c}
    return render(request, 'dash/index.html', context)

@login_required # Login decorator from Django
def courseView(request):
    context = {}
    return render(request, 'dash/index.html', context)

@login_required # Login decorator from Django
def editor(request):
    # Return python editor page
    return render(request, 'dash/editor.html', {})

@login_required # Login decorator from Django
def projectLessonView(request, slug):
    c = Course.objects.get(s=slug)
    l = Lesson.objects.filter(course=c.id)

    # If LessonProgress does not exist, create it for current user logged in
    for lesson in l:
        try:
            p = LessonProgress.objects.get(user = request.user, lesson = lesson)
        except LessonProgress.DoesNotExist:
            cr = LessonProgress.objects.create(user=request.user, lesson=lesson)
            cr.save()

    # Calculate amount of lessons to show
    total_lessons = l.count()
    not_complete = LessonProgress.objects.filter(user=request.user, completed=0).count()-1
    complete = LessonProgress.objects.filter(user=request.user, completed=1).count()
    show_lessons = total_lessons-not_complete
    display_more = False

    if complete - total_lessons == 0:
        # Set display_more flag to false
        display_more = False
    else:
        # Set flag to true
        display_more = True

    # Filter lesson progress model and show only limited number
    lp = LessonProgress.objects.filter(user=request.user)[:show_lessons]

    context = {'projectTitle': c.title, 'lessons': l, 'lesson_progress': lp, 'display_more': display_more}
    return render(request, 'dash/lessons.html', context)

@login_required # Login decorator from Django
def projectView(request):
    # Return all courses for project
    p = Course.objects.all()
    context = {'project': p}
    return render(request, 'dash/projects.html', context)

@login_required # Login decorator from Django
def logoutView(request):
    logout(request) # Use django logout function
    messages.add_message(request, messages.INFO, "You have been successfully logged out!")
    return redirect('front:index')

@login_required # Login decorator from Django
def checkAnswer(request):
    # Get answer id from ajax request
    answer = request.GET.get('answer_id')
    # Get quiz from answer id
    q = QuizAnswer.objects.get(id=answer)
    nextLessonID = q.question.quiz.lesson.id+1
    nextLesson = Lesson.objects.get(id = nextLessonID)
    question = q.question
    maxEntries = QuizQuestion.objects.filter(quiz_id=q.question.quiz.id).count()

    # Return data from the fileted queryset
    data = {
        'correct': q.correct,
        'max': maxEntries,
        'next': nextLesson.title
    }

    # Return as json object
    return JsonResponse(data)

@login_required # Login decorator from Django
def awardBadge(request):
    slug = request.GET.get('slug')
    action = request.GET.get('action')
    success = False

    # Elimitate user errors with try/except
    try:
        # Try to query the course model
        itemTitle = Course.objects.get(s=slug).title
    except:
        # If that fails query lesson model
        itemTitle = Lesson.objects.get(s=slug).title

    # Check if trophy exists, then award user or create it
    try:
        Trophies.objects.filter(title=slug).exists()
        t = Trophies.objects.get(title=slug)
        a = Award.award_user(request.user, t)
        success = True
    except:
        t = Trophies.create_trophy(action=action, title=itemTitle)
        new_t = Trophies.objects.get(title=itemTitle)
        a = Award.award_user(request.user, new_t)
        success = True


    data = {
        'success': success
    }

    return JsonResponse(data)

@login_required # Login decorator from Django
def workflow(request, project, lesson):
    l = Lesson.objects.get(s=lesson)
    q = QuizQuestion.objects.filter(quiz__lesson_id = l.id)
    qa = QuizAnswer.objects.all()

    # Check if a next lesson exists
    if Lesson.objects.filter(id=l.id+1).exists():
        nextL = Lesson.objects.get(id=l.id+1)
    else:
        nextL = Lesson.objects.get(id=l.id)

    # generate room name
    course_slug = l.course.s
    lesson_slug = l.s
    combine_slug = course_slug + lesson_slug
    room_name = combine_slug.replace('-', '')

    # Pass queryset to loop in template
    context = {
        'lesson': l, 
        'questions': q, 
        'answers': qa, 
        'next':nextL, 
        'room_name': mark_safe(json.dumps(room_name)),
        'username': mark_safe(json.dumps(request.user.username)),
    }
    return render(request, 'dash/workflow.html', context)

@login_required # Login decorator from Django
def updateLessonProgress(request):
    # Get lesson id
    lesson = request.GET.get('lesson')

    # Try/except for lesson progress to update it
    try:
        l = LessonProgress.objects.get(user=request.user, lesson_id=lesson)
        l.completed = True
        l.save()

        # Pass success true for ajax response
        data = {
            'success': True
        }
    except Exception as e:
        data = {
            'except': e
        }

    return JsonResponse(data)

@login_required # Login decorator from Django
def community(request):
    # Community page, pass roomname and username
    # Check that it is safe and dump json
    context = {
        'room_name': mark_safe(json.dumps("community")),
        'username': mark_safe(json.dumps(request.user.username)),
    }
    return render(request, 'dash/community.html', context)

@login_required # Login decorator from Django
def trophy(request):
    # Filter awards by user
    a = Award.objects.order_by('-awarded').filter(user=request.user)

    # Use Django Paginator
    page = request.GET.get('page', 1)
    paginator = Paginator(a, 3)

    try:
        a = paginator.page(page)
    except PageNotAnInteger:
        a = paginator.page(1)
    except EmptyPage:
        a = paginator.page(paginator.num_pages)

    context = {
        'award': a
    }

    return render(request, 'dash/trophy.html', context)

# Render activity view
@login_required # Login decorator from Django
def activity(request):
    s = Stream.objects.order_by('-when').filter(actor=request.user)

    # Use Django Paginator
    page = request.GET.get('page', 1)
    paginator = Paginator(s, 10)

    try:
        s = paginator.page(page)
    except PageNotAnInteger:
        s = paginator.page(1)
    except EmptyPage:
        s = paginator.page(paginator.num_pages)

    return render(request, 'dash/activity.html', {'stream': s})

# Render notification view
@login_required # Login decorator from Django
def notifications(request):
    # Filter notifcation object
    n = Notification.objects.order_by('-sent').filter(user=request.user)

    # Use Django Paginator
    page = request.GET.get('page', 1)
    paginator = Paginator(n, 5)

    try:
        n = paginator.page(page)
    except PageNotAnInteger:
        n = paginator.page(1)
    except EmptyPage:
        n = paginator.page(paginator.num_pages)

    return render(request, 'dash/notifications.html', {'notifications': n})

# Ajax notification to update
@login_required # Login decorator from Django
def notificationSeen(request):
    # Pass user object to user variable
    user = request.user

    # Update notifcation when seen
    try:
        notifications = Notification.objects.filter(seen=False, user=user)
        for n in notifications:
            n.seen = True
            n.save()
    except Exception:
        print("Failed")

    data = {
        'correct': True
    }

    return JsonResponse(data)

@login_required # Login decorator from Django
def getNotifications(request):
    user = request.user
    result = []
    # Get notifications per user
    try:
        n = Notification.objects.order_by('sent').filter(seen=False, user=user)
    except Exception:
        print("Failed")

    # Create json object for filtering in template
    for notifications in n:
        result.append({
            'content': notifications.content,
            'when': notifications.get_date()
        })

    data = {
        'correct': True,
        'notify': result,
        'count': n.count()
    }

    return JsonResponse(data)

# Leaderboards
@login_required # Login decorator from Django
def leaderboards(request):
    l = Award.objects.values('user', 'user__first_name', 'user__last_name').order_by('-total').annotate(total=Count('id'))

    # Use Django Paginator
    page = request.GET.get('page', 1)
    paginator = Paginator(l, 10)

    try:
        l = paginator.page(page)
    except PageNotAnInteger:
        l = paginator.page(1)
    except EmptyPage:
        l = paginator.page(paginator.num_pages)

    return render(request, 'dash/leaderboards.html', {'leaderboards': l})

@login_required # Login decorator from Django
def settings(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)

editor/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from dash.models import Course, Lesson, Instructions

# Create your views here.
@login_required
def index(request):
    return render(request, 'editor/index.html', {})

dash/templates/dash/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %} | CodeController</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'dash/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Page level plugin CSS-->
  <link href="{% static 'dash/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'dash/css/sb-admin.css' %}" rel="stylesheet">

<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<script src="{% static 'main.js' %}"></script>
<script src="{% static 'reconnecting-websocket.js' %}"></script>

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script> 

<script>
  function markRead(){
    x = Boolean($("#alertsDropdown").attr("aria-expanded"))

    if(x){
      $.ajax({
        url: '/ajax/view-notifications',
        data: {
            'user': '{{request.user|escapejs}}'
        },
        type: 'get',
        dataType: 'json',
        success: function (data) {
          if (data.correct) {
            $("#nCount").text("0");
          }
        }
      });
    }
  }

  var counter = 0;
  var oldNote = 0

  function getNotification(){
    $.ajax({
      url: '/ajax/get-notifications',
      type: 'get',
      dataType: 'json',
      success: function(data){
        $('#nCount').text(data.count);
        if(data.count > 0){
          if(oldNote == 0){
            for(let i = 0; i<data["notify"].length; i++){
              var child = document.getElementById('new-note');
              document.getElementById("alertsDropdown1").removeChild(child)
              getNewNotification(data["notify"][i]);
              oldNote++;
              
          }
          }
        } else {
          if(counter == 0){
            var parent = document.getElementById('alertsDropdown1');
            var a = document.createElement('a');
            a.classList.add('dropdown-item');
            a.setAttribute('id', 'new-note');
            a.setAttribute('href', '#');
            a.textContent = "No new notifications";
            var small = document.createElement('small');

            a.appendChild(small)
            parent.insertBefore(a, parent.firstChild); 
            counter++;
            oldNote = 0;
          } 
        }
      }
    });
  }

  $(document).ready(function(){
    setInterval(getNotification, 10000);
  });

  function getNewNotification(data){
    var parent = document.getElementById('alertsDropdown1');
    var a = document.createElement('a');
    a.classList.add('dropdown-item');
    a.setAttribute('href', '#');
    a.textContent = data.content;
    var small = document.createElement('small');
    small.textContent = data.when;

    a.appendChild(small)
    parent.insertBefore(a, parent.firstChild);
  }

  function createToast(data){
    var toast = document.createElement('div');
    toast.setAttribute('id', 'new-toast');
    toast.classList.add('toast');
    toast.setAttribute('role', 'alert');
    toast.setAttribute('aria-live', 'assertive');
    toast.setAttribute('aria-atomic', 'true');
    toast.setAttribute('data-autohide', 'false');
    toast.setAttribute('style', 'position: absolute; top: 0; right: 0;');

    var toastHeader = document.createElement('div');
    toastHeader.classList.add('toast-header');

    var str = document.createElement('strong');
    str.classList.add('mr-auto');
    str.textContent = "Notification";

    var sml = document.createElement('small');
    sml.classList.add('text-muted');
    sml.textContent = "Sent .....";

    var btn = document.createElement('button');
    btn.classList.add('ml-2', 'mb-1', 'close');
    btn.setAttribute('type', 'button');
    btn.setAttribute('data-dismiss', 'toast');
    btn.setAttribute('aria-label', 'Close');

    var span = document.createElement('span');
    span.setAttribute('aria-hidden', 'true');
    span.textContent = '&times;';

    var content = document.createElement('div');
    content.classList.add('toast-body');
    content.textContent = 'hello';

    toast.appendChild(toastHeader);
    toastHeader.appendChild(str);
    toastHeader.appendChild(sml);
    toastHeader.appendChild(btn);
    btn.appendChild(span);
    toastHeader.appendChild(content);
    document.getElementById('toastContent').appendChild(toast);

  }
</script>

  <!-- Quiz css -->
  <link href="{% static 'dash/css/quiz.css' %}">
  <script src="{% static 'dash/js/quiz.js' %}"></script>

  <!-- Change the height of the editor and output windows, below -->
  <style>
      #editor { 
  height: 150px;
}
#codeOutput {
  height: 150px;
}

  </style>
  <style>
  #btnTrigger
{
display:none;
}
</style>

<script>
  // clear the editor window
    function clearAceCode() {
              editor.setValue("");
          }
      </script>

<script type="text/javascript"> 
// The following scripts are slightly modified versions of the ones on the Skulpt web page  

// output functions are configurable.  This one just appends some text
// to a pre element.
function outf(text) { 
  var mypre = document.getElementById("codeOutput"); 
  mypre.innerHTML = mypre.innerHTML + text; 
} 
function builtinRead(x) {
  if (Sk.builtinFiles === undefined || Sk.builtinFiles["files"][x] === undefined)
      throw "File not found: '" + x + "'";
  return Sk.builtinFiles["files"][x];
}
// Here's everything you need to run a python program in skulpt
// grab the code from your textarea
// get a reference to your pre element for output
// configure the output function
// call Sk.importMainWithBody()

function runit() { 
  var prog = (editor.getValue());
  var mypre = document.getElementById("codeOutput");  
  mypre.innerHTML = ''; 
  Sk.pre = "codeOutput";
  Sk.configure({output:outf, read:builtinRead});
  var myPromise = Sk.misceval.asyncToPromise(function() {
    return Sk.importMainWithBody("<stdin>", false, prog, true);
  });
  myPromise.then(function(mod) {
    
  },
  function(err) {
    mypre.innerHTML = err.toString();
  });

  if(mypre.textContent === "Lesson 1"){
    console.log(mypre.textContent);
    console.log("True");
  } else {
    console.log("False");
    console.log(mypre.textContent);
  }
} 
// End of Skulp scripts

function clearConsole(){
  var console = document.getElementById('codeOutput');
  console.innerHTML = '';
}
</script> 
  

  {% block javascript %}{% endblock %}

</head>

<body id="page-top">

  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="{% url 'dash:index' %}">CodeController <i class="fas fa-terminal"></i></a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>




    <!-- Navbar -->
    <ul class="navbar-nav ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" onclick="markRead()" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span id="nCount" class="badge badge-danger">{{ total_notification }}</span>
          <i class="fas fa-bell fa-fw"></i>
        </a>

        <div id="alertsDropdown1" class="dropdown-menu dropdown-menu-right newNotifications" aria-labelledby="alertsDropdown">
          {% for n in prev_n %}
            <a class="dropdown-item" href="#">{{ n.content }}<small> {{ n.get_date }}</small></a>
          {% endfor %}
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'dash:notifications' %}">View all notifcations</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="{% url 'dash:settings' ">Settings</a>
          <a class="dropdown-item" href="{% url 'dash:activity' %}">Activity Log</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>
    </ul>

   

  </nav>



  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav toggled">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'dash:index' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span>
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'editor:index' %}" class="nav-link">
          <i class="fab fa-python"></i>
            <span>Python Editor</span></a>
        </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dash:projects' %} ">
          <i class="fas fa-chalkboard-teacher"></i>
          <span>Projects</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dash:trophies' %}">
          <i class="fas fa-trophy"></i>
          <span>Trophies</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dash:activity' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>Activity</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dash:community' %}">
          <i class="fas fa-hands-helping"></i>
          <span>Community</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dash:settings' %}">
          <i class="fas fa-users-cog"></i>
          <span>Account</span></a>
      </li>
    </ul>

    <div id="content-wrapper" class="d-flex flex-column">

      <div id="content" class="container-fluid">
        
        {% block content %}{% endblock%}

        
        
        </div>
      <!-- /.container-fluid -->


    </div>

    <div id="toastContent"></div>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'dash:logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'dash/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'dash/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'dash/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Page level plugin JavaScript-->
  <script src="{% static 'dash/vendor/chart.js/Chart.min.js' %}"></script>
  <script src="{% static 'dash/vendor/datatables/jquery.dataTables.js' %}"></script>
  <script src="{% static 'dash/vendor/datatables/dataTables.bootstrap4.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'dash/js/sb-admin.min.js' %}"></script>

  <!-- Demo scripts for this page-->
  <script src="{% static 'dash/js/demo/datatables-demo.js' %}"></script>
  <script src="{% static 'dash/js/demo/chart-area-demo.js' %}"></script>

  <script src="{% static 'dash/js/skulpt.min.js' %}"></script> 
  <script src="{% static 'dash/js/skulpt-stdlib.js' %}"></script> 


</body>

</html>